CREATE TABLE IF NOT EXISTS users (
                                     id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                     name VARCHAR(255) NOT NULL,
                                     email VARCHAR(512) NOT NULL,
                                     CONSTRAINT pk_user PRIMARY KEY (id),
                                     CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS items (
                                     id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                     name VARCHAR(255) NOT NULL,
                                     description TEXT NOT NULL,
                                     available BOOLEAN NOT NULL DEFAULT FALSE,
                                     owner_id BIGINT NOT NULL,
                                     CONSTRAINT pk_item PRIMARY KEY (id),
                                     CONSTRAINT fk_items_owner FOREIGN KEY (owner_id)
                                         REFERENCES users(id)
                                         ON DELETE CASCADE
                                         DEFERRABLE INITIALLY DEFERRED  -- Это важно!
);

CREATE TABLE IF NOT EXISTS bookings (
                                        id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                        start_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
                                        end_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
                                        item_id BIGINT NOT NULL,
                                        booker_id BIGINT NOT NULL,
                                        status VARCHAR(20) NOT NULL,
                                        created TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
                                        CONSTRAINT pk_booking PRIMARY KEY (id),
                                        CONSTRAINT fk_bookings_item FOREIGN KEY (item_id)
                                            REFERENCES items(id)
                                            ON DELETE CASCADE
                                            DEFERRABLE INITIALLY DEFERRED,
                                        CONSTRAINT fk_bookings_booker FOREIGN KEY (booker_id)
                                            REFERENCES users(id)
                                            ON DELETE CASCADE
                                            DEFERRABLE INITIALLY DEFERRED,
                                        CONSTRAINT chk_booking_dates CHECK (end_date > start_date)
);

CREATE TABLE IF NOT EXISTS comments (
                                        id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                        text TEXT NOT NULL,
                                        item_id BIGINT NOT NULL,
                                        author_id BIGINT NOT NULL,
                                        created TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
                                        CONSTRAINT pk_comment PRIMARY KEY (id),
                                        CONSTRAINT fk_comments_item FOREIGN KEY (item_id)
                                            REFERENCES items(id)
                                            ON DELETE CASCADE
                                            DEFERRABLE INITIALLY DEFERRED,
                                        CONSTRAINT fk_comments_author FOREIGN KEY (author_id)
                                            REFERENCES users(id)
                                            ON DELETE CASCADE
                                            DEFERRABLE INITIALLY DEFERRED
);

