-- Удаление существующих таблиц
DROP TABLE IF EXISTS comments CASCADE;
DROP TABLE IF EXISTS bookings CASCADE;
DROP TABLE IF EXISTS items CASCADE;
DROP TABLE IF EXISTS requests CASCADE;
DROP TABLE IF EXISTS users CASCADE;

-- Создание таблицы пользователей (users)
CREATE TABLE IF NOT EXISTS users (
                                     id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
                                     name VARCHAR(255) NOT NULL,
                                     email VARCHAR(512) NOT NULL,
                                     CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
);

-- Создание таблицы запросов вещей (requests)
CREATE TABLE IF NOT EXISTS requests (
                                        id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
                                        description TEXT NOT NULL,
                                        requester_id BIGINT NOT NULL,
                                        created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                        CONSTRAINT fk_requests_requester FOREIGN KEY (requester_id)
                                            REFERENCES users(id) ON DELETE CASCADE
);

-- Создание таблицы вещей (items) - ВАЖНО: есть request_id!
CREATE TABLE IF NOT EXISTS items (
                                     id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
                                     name VARCHAR(255) NOT NULL,
                                     description TEXT NOT NULL,
                                     available BOOLEAN NOT NULL DEFAULT FALSE,
                                     owner_id BIGINT NOT NULL,
                                     request_id BIGINT NULL,
                                     CONSTRAINT fk_items_owner FOREIGN KEY (owner_id)
                                         REFERENCES users(id) ON DELETE CASCADE,
                                     CONSTRAINT fk_items_request FOREIGN KEY (request_id)
                                         REFERENCES requests(id) ON DELETE SET NULL
);

-- Создание таблицы бронирований (bookings)
CREATE TABLE IF NOT EXISTS bookings (
                                        id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
                                        start_date TIMESTAMP NOT NULL,
                                        end_date TIMESTAMP NOT NULL,
                                        item_id BIGINT NOT NULL,
                                        booker_id BIGINT NOT NULL,
                                        status VARCHAR(20) NOT NULL,
                                        created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                                        CONSTRAINT fk_bookings_item FOREIGN KEY (item_id)
                                            REFERENCES items(id) ON DELETE CASCADE,
                                        CONSTRAINT fk_bookings_booker FOREIGN KEY (booker_id)
                                            REFERENCES users(id) ON DELETE CASCADE,
                                        CONSTRAINT chk_booking_dates CHECK (end_date > start_date)
);

-- Создание таблицы комментариев (comments)
CREATE TABLE IF NOT EXISTS comments (
                                        id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
                                        text TEXT NOT NULL,
                                        item_id BIGINT NOT NULL,
                                        author_id BIGINT NOT NULL,
                                        created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                                        CONSTRAINT fk_comments_item FOREIGN KEY (item_id)
                                            REFERENCES items(id) ON DELETE CASCADE,
                                        CONSTRAINT fk_comments_author FOREIGN KEY (author_id)
                                            REFERENCES users(id) ON DELETE CASCADE
);