server.port=8080
spring.application.name=shareit-gateway
shareit-server.url=http://localhost:9090

spring.jackson.serialization.write-dates-as-timestamps=false
spring.jackson.time-zone=UTC

logging.level.ru.practicum.shareit.gateway=DEBUG
logging.level.org.springframework.web.client.RestTemplate=DEBUG
logging.level.org.springframework.web=DEBUG

logging.level.org.apache.http.wire=DEBUG
logging.level.org.apache.http.headers=DEBUG